---
title: "Results"
author: "Anne"
date: "4/11/2020"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_float: yes

---


```{r}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE)

```


```{r}
library(readxl)
library(kableExtra)
library(ggplot2)
library(dplyr)
library(stringr)
library(ggpubr)
library(ggthemes)
library("RColorBrewer")

data = readRDS("./data_2017.rds") 


```


```{r}
data$recip_agegroups <- cut(data$recip_age, 
                   breaks=c(0, 18, 40, 60, Inf), right = FALSE)

data$PRA_cat <- cut(data$recip_pra, 
                   breaks=c(0, 50, 80, Inf), right = FALSE)

index <- which(data$recip_state %in% c("NZ", NA) | data$donor_state %in% c("NZ", NA) )
data <- data[-index,] %>% as.data.frame()


tx_donor <- as.character(unlist(data$donor_state))
data$tx_donor<- sapply(tx_donor, function(x) switch(as.character(x),
                                              NSW = "NSW", ACT = "NSW",
                                              VIC = "VIC", TAS = "VIC",
                                              SA = "SA", NT = "SA",
                                              WA = "WA", QLD = "QLD"))



data <- data %>% 
  mutate(recip_listtime = as.numeric(as.character(recip_listtime))/365,
         recip_waittime = as.numeric(as.character(recip_waittime))/365,
        tx_donor = as.factor(as.character(tx_donor))) %>%
  mutate(eth_recip = ifelse(recip_eth_detailed == "Caucasoid", "European", "Other"),
         eth_recip = replace(eth_recip, str_detect(recip_eth_detailed, "Australian"), "European"),
         eth_recip = replace(eth_recip, str_detect(recip_eth_detailed, "North American"), "European"),
         eth_recip = replace(eth_recip, recip_eth_detailed== "Oceanian - Australian Aboriginal" |  str_detect(recip_eth_detailed, "Torre"),"Indigenous Australians"),
         eth_recip = replace(eth_recip, str_detect(recip_eth_detailed, "European"), "European"), 
         eth_recip = as.factor(eth_recip),
         
         eth_donor = ifelse(donor_eth_code == "Caucasoid", "European", "Other"),
         eth_donor = replace(eth_donor, str_detect(donor_eth_code, "Australian"), "European"),
         eth_donor = replace(eth_donor, str_detect(donor_eth_code, "North American"), "European"),
         eth_donor = replace(eth_donor, donor_eth_code== "Oceanian - Australian Aboriginal" |  str_detect(donor_eth_code, "Torre"),  "Indigenous Australians"),
         eth_donor = replace(eth_donor, str_detect(donor_eth_code, "European"), "European"), 
         eth_donor = as.factor(eth_donor))%>% mutate(graft_cat = ifelse(recip_graftno == 1, "1", "2+")) %>%
  as.data.frame()
#data %>% dplyr::select(recip_eth_detailed, eth_recip,donor_eth_code, eth_donor )


```


```{r}

source("./allocation_algorithm.R")
HLA<- data %>% dplyr::select(tx_misa, tx_misb, tx_misdr)

original_score <- allocation_national(data,data,HLA)
table(original_score < 54000000)
data$algorithm <- ifelse(original_score >= 54000000,
                            "National", "State")

max(data$tx_date)
```
# Tables

```{r}
data %>% group_by(algorithm, recip_state) %>% summarise(n=n(), med = median(recip_listtime), range = IQR(recip_listtime)) %>% mutate(prop = n/sum(n))

data %>% group_by(algorithm, PRA_cat, recip_state) %>% summarise(n=n(), med = median(recip_listtime), range = IQR(recip_listtime)) %>% mutate(prop = n/sum(n)) %>% filter(PRA_cat == "[80,Inf)")


data %>% group_by(recip_sex, PRA_cat) %>% summarise(n=n(), med = median(recip_listtime), range = IQR(recip_listtime)) %>% mutate(prop = n/sum(n))


nrow(data)
length(unique(data$donor_id))
```

# Output IQR ranges

```{r}
library(purrr)
p <- c(0.25, 0.5, 0.75)
p_names <- map_chr(p, ~paste0(.x*100, "%"))
p_funs <- map(p, ~partial(quantile, probs = .x, na.rm = TRUE)) %>% 
  set_names(nm = p_names)
p_funs


data %>% 
  group_by(algorithm, recip_state) %>% 
  summarize_at(vars(recip_listtime), funs(!!!p_funs))

data %>% 
  group_by(algorithm, PRA_cat, recip_state) %>% 
  summarize_at(vars(recip_listtime), funs(!!!p_funs))

```



```{r}

algorithm <- data %>%
  count(algorithm) %>%
  mutate(proportion = n/sum(n)) %>%
  mutate(proportion = round(proportion,2)*100)

age_group <- data %>%
  group_by(algorithm, recip_agegroups) %>%
  count()

pra_group <- data %>% group_by(algorithm, PRA_cat,recip_sex) %>%  summarise(n=n(), median = median(recip_listtime), IQR = IQR(recip_listtime)) %>% filter(PRA_cat == "[80,Inf)")
pra_group$PRA_cat <- c("80+")

eth <- data %>% mutate(replace(eth_recip, eth_recip == "Aboriginal/ Torres Strait Islander", "Indigenous Australian"))%>% group_by(algorithm, eth_recip) %>%  summarise(n=n(), median = median(recip_listtime),IQR = IQR(recip_listtime)) %>% tidyr::drop_na() %>% ungroup()



```

```{r}
kable(algorithm, col.names = c("Algorithm", "No. per regime", "Proportion (%)"), caption = "Table 1: Amount of people allocated under the National and State Allocation Framework" )%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F) %>%
  row_spec(c(2), bold = T, color = "black", background = "lightblue")

kable(age_group, col.names = c("Algorithm", "Age Group", "No. of recipients"), caption = "Table 2: Age demographics of kidney transplant recipients under the National and State Allocation Framework")%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F) %>%
  row_spec(c(2,3,6,7), bold = T, color = "black", background = "lightblue")

kable(pra_group,col.names = c("Algorithm","PRA", "Sex", "No. of recipients", "Median time", "IQR"), caption = "Table 3: Demographics and median list to transplant time of sensitised recipients under the National and State Allocation Framework", digits=2) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F) %>%
  row_spec(c(3,4), bold = T, color = "black", background = "lightblue")

kable(eth,col.names = c("Algorithm", "Ethnicity", "No. of recipients", "Median time", "IQR"), digits = 2, caption = "Table 4: Median list to transplant time for recipients of different ethnicities under the National and State Allocation Framework") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F) %>%
  row_spec(c(4,5,6), bold = T, color = "black", background = "lightblue")


```
```{r}
donor_data <- data %>% dplyr::select(tx_date, donor_id, tx_donor) %>% mutate(year = lubridate::year(tx_date), donor_id = as.character(donor_id)) %>% filter(year %in% c("2012", "2013","2014", "2015","2016", "2017")) 

donor_data<- donor_data[!duplicated(donor_data$donor_id),]
population_data <- donor_data %>% group_by(year, tx_donor) %>% summarise(n=n())

waitlist_o <- read_excel("./waitlist_pop.xlsx")

waitlist_o <- reshape2::melt(waitlist_o, id.vars=c("Modality", "recip_state"), variable.name="year", value.name = "waitlist")

waitlist_o <- merge(waitlist_o, population_data, by.x = c("recip_state", "year"), by.y = c("tx_donor", "year")) %>% mutate(prop = n/as.numeric(as.character(waitlist)))
waitlist_o <- merge(waitlist_o, donor_data, by.x = c("recip_state", "year"), by.y= c("tx_donor", "year")) %>% mutate(prop = as.numeric(as.character(prop)))


waitlist_o <- waitlist_o %>% dplyr::select(recip_state, prop, year) 
waitlist_o<- waitlist_o[!duplicated(waitlist_o),]

level = c("NSW", "VIC","QLD", "SA", "WA")
waitlist_o$recip_state <- factor(waitlist_o$recip_state,levels = level)
waitlist_o %>% filter(year %in% c(2012, 2017)) 

```
```{r}
level = c("NSW", "VIC","QLD", "SA", "WA")
data$recip_state <- factor(data$recip_state,levels = level)

level = c("NSW", "VIC","QLD", "SA", "WA")
data$tx_donor <- factor(data$tx_donor,levels = level)

data$tx_year <- format(as.Date(data$tx_date), format = "%Y")


balance_year <-table(data$tx_year, data$recip_state)-table(data$tx_year, data$tx_donor) 
balance_year<- reshape2::melt(balance_year, id.vars=c("state", "Count"))
balance_year$type <- ifelse(balance_year$value >0, "Excess transplants", "Deficit of transplants")
colnames(balance_year) <- c("year", "state", "Count", "Type")
balance_year$year <- as.factor(balance_year$year )

balance_year %>% group_by(state) %>% summarise(count = sum(Count))
```


```{r}
level = c("NSW", "VIC","QLD", "SA", "WA")
data$recip_state <- factor(data$recip_state,levels = level)
data$tx_year <- lubridate::year(data$tx_date)

year<- data %>% mutate(year = lubridate::year(tx_date)) %>%
  group_by(recip_state, year, algorithm) %>%
  summarise(median=median(recip_listtime), first = quantile(recip_listtime)[2] , third = quantile(recip_listtime)[4]  , n=n()) 

year %>% arrange(desc(median))

```

# Density plots of kidney recipients

```{r}
data %>% ggplot(aes(x=recip_listtime)) +geom_density(aes(fill = recip_state), alpha = 0.5) + facet_grid(~recip_state)+ labs(y="Density", x="Time from list to transplantation (years)") + theme_bw() + scale_fill_tableau() + theme(aspect.ratio = 1.5, legend.position = "none")

ggsave("listtimedensity.pdf")

data %>% ggplot(aes(x=recip_waittime)) + geom_density(aes(fill = recip_state), alpha = 0.5) + facet_grid(~recip_state)+ labs(y="Density", x="Waiting time (years)") + theme_bw()+ scale_fill_tableau()+ theme(aspect.ratio = 1.5, legend.position = "none")
ggsave("waittimedensity.pdf")

```





# Map of Australia 

```{r}

library(ozmaps)
library(ggplot2)


ozmap_states$State <- c("NSW", "VIC", "QLD","SA","WA", "VIC","SA", "NSW", "Other")
ozmap_states$State <- factor(ozmap_states$State, levels = c("NSW", "VIC", "QLD", "SA", "WA", "Other"))

index <- which(ozmap_states$State == "Other")
ozmap_states<-ozmap_states[-index,]


colours <- c("#993333", "#FF9999", "#CCCCCC", "#6699FF", "#003399", "#FFFFFF")

ggplot(ozmap_states) +
  geom_sf(aes(fill = State), alpha = 0.7) +
  geom_text(x = 147, y=-32, label = "2.7", size = 7)+ 
  geom_text(x = 145, y=-37, label = "1.3", size = 3.5)+ 
  geom_text(x = 122, y=-25, label = "0.21", size = 5.5)+ 
  geom_text(x = 135, y=-29, label = "0.4", size = 5)+ 
  geom_text(x = 145, y=-23, label = "0.42", size = 5)+ 
  theme_bw() + 
 scale_fill_manual(values = colours)




```

# Primary cause of renal disease

```{r}
# Primary cause of renal disease
sort(summary(as.factor(data$recip_primrenal)), decreasing = TRUE)[1]/sum(summary(as.factor(data$recip_primrenal)))*100


```

# Waiting list

```{r}

active_patients = readRDS("./active_patients.rds") 

active_patients %>% ggplot(aes(x=recip_listtime)) +geom_density(aes(fill = waitstat), alpha = 0.5) + facet_grid(~waitstat)+ labs(y="Density", x="Time from first active on list to last recorded date 2018 (years)") + theme_bw() + scale_fill_tableau() + theme(aspect.ratio = 1.5, legend.position = "none")

active_patients %>% ggplot(aes(x=recip_waittime)) +geom_density(aes(fill = waitstat), alpha = 0.5) + facet_grid(~waitstat)+ labs(y="Density", x="Waiting Time to 2018 (years)") + theme_bw() + scale_fill_tableau() + theme(aspect.ratio = 1.5, legend.position = "none")


active_patients %>% 
  group_by(waitstat) %>% 
  summarise( median_wait = median(recip_waittime), 
             iqr_wait = IQR(recip_waittime),
             n=n())

active_patients %>% 
  group_by(waitstat) %>% 
  summarize_at(vars(recip_waittime), funs(!!!p_funs))

```

# Mortality on the waitlist 

```{r}
wait_p_death = readRDS("./wait_p_death.rds") 

wait_p_death$waitstat <- factor(wait_p_death$waitstat, levels=c("NSW", "VIC", "QLD", "SA", "WA"))

wait_p_death<-wait_p_death %>% group_by(id) %>%
    filter(waitseq == max(waitseq))

wait_p_death %>% ggplot(aes(x = waitstat, fill = waitstat)) + geom_bar(alpha = 0.8)+ theme_bw() + scale_fill_tableau() + theme(aspect.ratio = 1, legend.position = "none") + labs(x= "State", y= "Frequency")

wait_p_death$waityear <- lubridate::year(lubridate::dmy(wait_p_death$waitdate))

wait_p_death%>% group_by(waityear, waitstat) %>% summarise(n=n()) %>% ggplot(aes(x= waitstat, y = n, fill = waitstat)) + geom_col( alpha =0.8) +facet_wrap(~waityear)+ theme_bw() + scale_fill_tableau() + theme(aspect.ratio = 0.5, legend.position = "none") + labs(x= "State", y= "Frequency", title = "Mortality")



```

# Table of characteristics by state

```{r}

col_title <- c("Group", "NSW", "VIC","QLD", "SA", "WA")

sex_long <- data %>% 
  group_by(recip_state, recip_sex) %>% 
  summarise(n=n()) %>% mutate(n = paste(n, paste(round(n/sum(n)*100,1), ")", sep = ""), sep = " (" ))
sex_wide <- tidyr::pivot_wider(sex_long, names_from = recip_state, values_from = n)
colnames(sex_wide) <- col_title
sex_wide <- cbind( Characteristics= c("Sex (n,%)", rep(" ", nrow(sex_wide)-1)), sex_wide)



PRA_long <- data %>% 
  group_by(recip_state, PRA_cat) %>% 
  summarise(n=n()) %>% mutate(n = paste(n, paste(round(n/sum(n)*100,1), ")", sep = ""), sep = " (" ))
PRA_wide <- tidyr::pivot_wider(PRA_long, names_from = recip_state, values_from = n)
colnames(PRA_wide) <- col_title
PRA_wide <- cbind( Characteristics= c("PRA Group (n,%)", rep(" ", nrow(PRA_wide)-1)), PRA_wide)


blg_long <- data %>% 
  group_by(recip_state, recip_blgroup) %>% 
  summarise(n=n()) %>% mutate(n = paste(n, paste(round(n/sum(n)*100,1), ")", sep = ""), sep = " (" ))
blg_wide <- tidyr::pivot_wider(blg_long, names_from = recip_state, values_from = n)
colnames(blg_wide) <- col_title
blg_wide <- cbind( Characteristics= c("Blood Group", rep(" ", nrow(blg_wide)-1)), blg_wide)


eth_long<- data %>% 
  group_by(recip_state, eth_recip) %>% 
  summarise(n=n()) %>% mutate(n = paste(n, paste(round(n/sum(n)*100,1), ")", sep = ""), sep = " (" ))
eth_wide <- tidyr::pivot_wider(eth_long, names_from = recip_state, values_from = n)
colnames(eth_wide) <- col_title
eth_wide <- cbind( Characteristics= c("Ethicity (n,%)", rep(" ", nrow(eth_wide)-1)), eth_wide)


age_long <- data %>% 
  group_by(recip_state, recip_agegroups) %>% 
  summarise(n=n()) %>% mutate(n = paste(n, paste(round(n/sum(n)*100,1), ")", sep = ""), sep = " (" ))
age_wide <- tidyr::pivot_wider(age_long, names_from = recip_state, values_from = n)
colnames(age_wide) <- col_title
age_wide <- cbind( Characteristics= c("Age Group (n,%)", rep(" ", nrow(age_wide)-1)), age_wide)


diabetes_long <- data %>% 
  group_by(recip_state, diabetescode_text) %>% 
  summarise(n=n()) %>% mutate(n = paste(n, paste(round(n/sum(n)*100,1), ")", sep = ""), sep = " (" ))
diabetes_wide <- tidyr::pivot_wider(diabetes_long, names_from = recip_state, values_from = n)
colnames(diabetes_wide) <- col_title
diabetes_wide <- cbind( Characteristics= c("Diabetes (n,%)", rep(" ", nrow(diabetes_wide)-1)), diabetes_wide)



lung_long <- data %>% 
  group_by(recip_state, recip_lung) %>% 
  summarise(n=n()) %>% mutate(n = paste(n, paste(round(n/sum(n)*100,1), ")", sep = ""), sep = " (" ))
lung_wide <- tidyr::pivot_wider(lung_long, names_from = recip_state, values_from = n)
colnames(lung_wide) <- col_title
lung_wide <- cbind( Characteristics= c("Lung Disease (n,%)", rep(" ", nrow(lung_wide)-1)), lung_wide)


pvd_long <- data %>% 
  group_by(recip_state, recip_pvd) %>% 
  summarise(n=n()) %>% mutate(n = paste(n, paste(round(n/sum(n)*100,1), ")", sep = ""), sep = " (" ))
pvd_wide <- tidyr::pivot_wider(pvd_long, names_from = recip_state, values_from = n)
colnames(pvd_wide) <- col_title
pvd_wide <- cbind( Characteristics= c("Peripheral Vascular Disease (n,%)", rep(" ", nrow(pvd_wide)-1)), pvd_wide)


cvd_long <- data %>% 
  group_by(recip_state, recip_cvd) %>% 
  summarise(n=n()) %>% mutate(n = paste(n, paste(round(n/sum(n)*100,1), ")", sep = ""), sep = " (" ))
cvd_wide <- tidyr::pivot_wider(cvd_long, names_from = recip_state, values_from = n)
colnames(cvd_wide) <- col_title
cvd_wide <- cbind( Characteristics= c("Cerebrovascular Disease (n,%)", rep(" ", nrow(cvd_wide)-1)), cvd_wide)


coronary_long <- data %>% 
  group_by(recip_state, recip_coronary) %>% 
  summarise(n=n()) %>% mutate(n = paste(n, paste(round(n/sum(n)*100,1), ")", sep = ""), sep = " (" ))
coronary_wide <- tidyr::pivot_wider(coronary_long, names_from = recip_state, values_from = n)
colnames(coronary_wide) <- col_title
coronary_wide <- cbind( Characteristics= c("Coronary artery Disease (n,%)", rep(" ", nrow(coronary_wide)-1)), coronary_wide)



#colnames(data)

characteristics <- rbind(
  sex_wide,
  age_wide, 
  blg_wide, 
  eth_wide,
  PRA_wide,
  diabetes_wide, 
  lung_wide, 
  cvd_wide, 
  pvd_wide, 
  coronary_wide
) %>% tidyr::drop_na(Group)

#characteristics <- na.omit(characteristics)
characteristics
```


```{r}
waitlist <- read.csv("./42510_paeds_allocation_project/waitlist.csv",na.strings=c("-" ," ", "","NA"))
waitlist$waityear <- lubridate::year(lubridate::dmy(waitlist$waitdate))
waitlist_removal <- waitlist[which(is.na(waitlist$waitorgans) & waitlist$waitstatus != "Active"),]

waitlist_removal%>% group_by(id, waitstat, waityear) %>% summarise(n=n()) %>% group_by( waitstat, waityear) %>% summarise(n=n())%>% ggplot(aes(x=waitstat, y=n, fill=waitstat)) + 
geom_col(alpha = 0.8) + facet_wrap(~waityear)+ theme_bw() + scale_fill_tableau() + theme(aspect.ratio = 0.5, legend.position = "none") + labs(x= "State", y= "Frequency", title = "Delisting")



```

